export const INITIAL_PATH="/"
export const LEAD_DETAILS_PATH = "/lead/:lead_id"
export const ACTIVITIES_PATH = "/lead/:lead_id/activities"
export const REMARK_PATH = "/lead/:lead_id/remark"
export const DOCS_PATH="/lead/:lead_id/documents"
export const CALL_LOG_PATH="/lead/:lead_id/call"
export const HISTORY_PATH="/lead/:lead_id/history"

export const DATE_FORMAT="DD/MM/YYYY"

export const FILED_EMAIL="EMAIL"
export const FILED_PHONE="PHONE_NUMBER"
export const FILED_SMALL_TEXT="SMALL_TEXT"
export const FILED_LONG_TEXT="LONG_TEXT"
export const FILED_DROPDOWN="DROPDOWN"
export const FILED_NUMBER="NUMBER"
export const FILED_DATE="DATE"
export const FILED_MULTI_SELECT="MULTI_SELECT"
export const FILED_CHECKBOX_GROUP="CHECKBOX_GROUP"
export const IDENTIFY_URL="http"
