export const LEAD_DETAILS_PATH = "/"
export const ACTIVITIES_PATH = "/activities"
export const REMARK_PATH = "/remark"
export const DOCS_PATH="/documents"
export const CALL_LOG_PATH="/call"
export const HISTORY_PATH="/history"

export const DATE_FORMAT="DD/MM/YYYY"

export const FILED_EMAIL="EMAIL"
export const FILED_PHONE="PHONE_NUMBER"
export const FILED_SMALL_TEXT="SMALL_TEXT"
export const FILED_LONG_TEXT="LONG_TEXT"
export const FILED_DROPDOWN="DROPDOWN"
export const FILED_NUMBER="NUMBER"
export const FILED_DATE="DATE"
export const FILED_MULTI_SELECT="MULTI_SELECT"
export const FILED_CHECKBOX_GROUP="CHECKBOX_GROUP"
export const IDENTIFY_URL="http"
